export const projects = [
  {
    title: 'Go vs CUDA Neural Network Inference',
    description: "A university project to compare inference performance between CUDA on a GPU and Go running in parallel on the CPU.",
    objectives: ["Improve CUDA knowledge.", "Improve Golang knowledge.", "Explore Go parallelism.", "To write NN inference for the MNIST dataset from scratch."],
    image: './images/5.png',
    tags: ['CUDA', 'C++', 'Golang', 'ML'],
    id: 0,
  },
  {
    title: 'React Portfolio',
    description: "A personal portfolio in React.",
    objectives: ["Single page and elegant design.", "Tutorial - An example to build upon and customize.", "Mobile friendly.", "Compatible with Github Pages."],
    image: './images/1.png',
    tags: ['React.js', 'Next.js', 'Node'],
    source: 'https://github.com/FlyLikeAPenguin/React-Portfolio',
    visit: 'https://flylikeapenguin.github.io/React-Portfolio/',
    id: 1,
  },
  {
    title: 'Genki Flashcards',
    description: "A react webapp companion to the genki textbooks for Kanji/Kana.",
    objectives: ["A fully featured flashcards app.", "User's lesson selection persists between sessions.", "Compatible with Github Pages.", "Mobile friendly."],
    image: './images/2.png',
    tags: ['React.js', 'JSON', 'Node'],
    source: 'https://github.com/FlyLikeAPenguin/Genki-Flashcards',
    visit: 'https://flylikeapenguin.github.io/Genki-Flashcards/',
    id: 2,
  },
  {
    title: 'Python Gold',
    description: "The gold medal for python on Hackerrank.",
    objectives: ["To revise the fundamentals of python.", "Practice Algorithms & Data Structures."],
    image: './images/3.png',
    tags: ['Python', 'Challenges', 'Hackerrank'],
    visit: 'https://www.hackerrank.com/FlyLikeAPenguin',
    id: 3,
  },
  {
    title: 'IdleSat',
    description: "A satellite themed 'Idle' Game created in the Unity engine.",
    objectives: ["Exploring game mechanics in Unity.", "Creating graphics/UI elements.", "Understanding Unity project layout.", "Learning how Unity connects objects."],
    image: './images/4.gif',
    tags: ['Unity', 'C#', 'Game'],
    id: 4,
  },
  {
    title: 'Satellite Orbital Simulator & Tracker',
    description: "A fully 3D orbital simulation with forward/backward propagation and ground-station pass calculation.",
    objectives: ["Forwards and backwards orbit propagation.", "Calculation of ground-station passes."],
    image: './images/6.png',
    tags: ['ReactJS', 'Javascript', 'CesiumJS'],
    visit: 'https://flylikeapenguin.github.io/Satboard/?gs=78.2298,15.4078',
    source: 'https://github.com/FlyLikeAPenguin/Satboard',
    id: 6,
  },
  {
    title: 'Mission Countdown',
    description: "A simple mission countdown app with milestones to use during satellite launch and early operation.",
    objectives: ["Simple mission situational awareness.", "Fireworks for fun and entertainment."],
    image: './images/7.png',
    tags: ['ReactJS', 'Javascript', 'FireworksJS'],
    visit: 'https://flylikeapenguin.github.io/MissionCountdown/',
    source: 'https://github.com/FlyLikeAPenguin/MissionCountdown',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Completed BSc Computer Science - 1st Class (Hons)', },
  { year: 2018, text: 'Completed PGCE in Computing (Teacher Training)', },
  { year: 2018, text: 'Started work at LabLogic Systems as a C# .Net Developer', },
  { year: 2020, text: 'LabLogic - Designed, Managed & Completed a .Net Core REST API', },
  { year: 2021, text: 'Created Personal Portfolio using React.js & Next.js', },
  { year: 2021, text: 'Created Genki Flashcards using React.js', },
  { year: 2022, text: 'Got First Gold Badge on Hackerrank (Python)', },
  { year: 2023, text: 'Moved to Japan to Work as a DevOps Engineer on Satellite Ground-systems', },
  { year: 2023, text: 'Promoted to Senior Software Engineer for Satellite Ground-systems', },
  { year: 2024, text: 'Promoted to Team Leader for Satellite Data Acquisition and Delivery', },
];
